% This script defines the subject details for 'fil_mri_organise_batch'

load('D:\Documents\software\MetaLabCore\project_params.mat');

%% SUBJECT DETAILS
% subject 1: 01RoYi
subj{1} = struct(...
                'scanid', 'MP02312',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]);

% subject 2: 02XiHo
subj{2} = struct(...
                'scanid', 'MP02313',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]);
            
% subject 3: 03JaVe
subj{3} = struct(...
                'scanid', 'MP02319',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:11,...
                'fieldmaps', [4 5]);

% subject 4: 04NiSi
subj{4} = struct(...
                'scanid', 'MP02320',...
                'localiser',  1,...
                'structural', 2,...
                'functional', [6 7 9 10 11],...
                'fieldmaps', [4 5]);
            
% subject 5: 05PeYa
subj{5} = struct(...
                'scanid', 'MP02336',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]);
            
% subject 6: 06KuSh 
subj{6} = struct(...
                'scanid', 'MP02324',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]);
            
% subject 7: 07AnWo 
subj{7} = struct(...
                'scanid', 'MP02325',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 7:11,...
                'fieldmaps', [5 6]);
            
% subject 8: 08LiBa 
subj{8} = struct(...
                'scanid', 'MP02327',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]);  
            
% subject 9: 09KeVa
subj{9} = struct(...
                'scanid', 'MP02328',...
                'localiser',  [],...
                'structural', 3,...
                'functional', [9:12,14],...
                'fieldmaps', [7 8]);

% subject 10: 10MaIv
subj{10} = struct(...
                'scanid', 'MP02332',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]); 
            
% subject 11: 11YaSi
subj{11} = struct(...
                'scanid', 'MP02333',...
                'localiser',  [],...
                'structural', 19,...
                'functional', [13 14 15 16 20],...
                'fieldmaps', [18 19]); 
            
% subject 12: 12JaGu
subj{12} = struct(...
                'scanid', 'MP02337',...
                'localiser',  1,...
                'structural', 2,...
                'functional', [9 10 11 13 14],...
                'fieldmaps', [6 7]); 

% subject 13: 13ChSc
subj{13} = struct(...
                'scanid', 'MP02338',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]); 
            
% subject 14: 14SaMc
subj{14} = struct(...
                'scanid', 'MP02339',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]); 

% subject 15: 15ChFi
subj{15} = struct(...
                'scanid', 'MP02341',...
                'localiser',  1,...
                'structural', 2,...
                'functional', 6:10,...
                'fieldmaps', [4 5]); 
            

%% Save details
save(fullfile(project_params.raw_dir,'subject_details.mat'),'subj');
